version: '3.8'

services:
  spring-app:
    build:
      context: ./api-imobiliaria
      dockerfile: Dockerfile
    image: api-imobiliaria:latest
    container_name: api-imobiliaria
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/imobiliaria

  mongo:
    image: mongo:latest
    container_name: mongo-imobiliaria
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
