version: '3.8'

services:
  spring-app:
    build:
      context: ./api-imobiliaria
      dockerfile: Dockerfile
    container_name: api-imobiliaria
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      # Variável de ambiente para a conexão com o MongoDB (exemplo para Spring Boot)
      SPRING_DATA_MONGODB_URI: mongodb+srv://viniciusgomesserrano:hjF0oYqe951hlJlg@cluster0.k2iwn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  mongo:
    image: mongo:latest
    container_name: mongo-imobiliaria
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
