# prometheus.yml

# 1) Definimos o intervalo de coleta e avaliação
global:
  scrape_interval:     15s  # com que frequência o Prometheus "scrapa" todo mundo
  evaluation_interval: 15s  # com que frequência avalia regras de gravação, alertas, etc.

scrape_configs:
  # Seu serviço de imóveis
  - job_name: 'api-imobiliaria'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-imobiliaria-endereco.onrender.com','api-imobiliaria:8080']

  # Seu serviço de endereços
  - job_name: 'api-imobiliaria-endereco'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-imobiliaria-endereco.onrender.com','api-imobiliaria-endereco:8088']

  # Prometheus scrapping itself (útil para saber saúde, GC, etc)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
